# Welcome to Jekyll!
 github: [metadata]
 kramdown:
   input: GFM
   hard_wrap: false
 gems:
   - jekyll-coffeescript
   - jekyll-paginate

# Site settings
title: 
description: |
  Kadenze Course on Daniel Shiffman http://natureofcode.com
  in P5.js 
owner: Marinella Mastrosimone # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: marinella.mastrosimone@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marinella.mastrosimone.eu" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<cybermarinella>
  github: https://github.com/<cybermarinella>
  linkedin-square: https://it.linkedin.com/in/cybermarinella
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
